### ISSUE TITLE
The orb source mismatches what's in github. Did your CI fail?

### ISSUE THREAD

**Issue by owenallenaz** [atlassian-labs/Compass-Orb#13]
Looking at the orb source listed on version 0.1.2 @ https://circleci.com/developer/orbs/orb/atlassian-labs/compass we can see that the orb code contains the issue with it not actually using the `environment` parameter. Notice how `displayName` is erroneously set to `$environmentType`.

```
"deployments": [
  {
      "environment": {
        "category": $category,
        "displayName": $environmentType,
        "environmentId": $environmentType
      },
    "lastUpdated": $lastUpdated
  }
```

But if we look at the source of this repo, it has the correction: https://github.com/atlassian-labs/Compass-Orb/blob/main/src/scripts/notify_deployment.sh#L32C1-L40C8 .

I notice that the last merged pull request failed in your CI, is it possible that the orb didn't version off a new version? We're trying to implement our systems with Compass and we need the `displayName` since we have to tag everything as `production` otherwise it doesn't show up.

**Comment by sbland2** [comment]
Hi @owenallenaz thank you for the heads up! We have fixed the pipeline issues and published a new version of the orb.
